version: '3'
services:

    web:
        image: nginx:latest
        container_name: "app_nginx"
        ports:
            - "8080:80"
        volumes:
            # - "./html:/usr/share/nginx/html"
            - "./app:/app"
            - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
            - "./nginx/conf.d:/etc/nginx/conf.d"
        restart: always
        depends_on:
            - php
            - db
    
    php:
        build: ./php
        restart: always
        container_name: "app_php"
        volumes:
            - "./app:/app"
            - ./php/php.ini:/usr/local/etc/php/conf.d/php.ini
            - ./php/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
   
    db:
        image: postgres:9.6
        container_name: "app_postgres"
        restart: always
        environment:
            # - POSTGRES_DB=${DB_NAME}
            # - POSTGRES_USER=${DB_USER}
            # - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=demodb
            - POSTGRES_USER=mike
            - POSTGRES_PASSWORD=password
        ports:
            - 5432:5432
        volumes:
            - ./postgres/data/:/var/lib/postgresql/data/
    
    pgadmin4:
        image: dpage/pgadmin4
        container_name: "app_pgadmin4"
        restart: always
        environment:
            - PGADMIN_DEFAULT_EMAIL=karasavm@gmail.com
            - PGADMIN_DEFAULT_PASSWORD=123456
        ports:
            - 8081:80
       
    # adminer:
    #     container_name: "adminer"
    #     image: adminer
    #     restart: always
    #     ports:
    #     - 8081:8080

    composer:
        container_name: "app_composer"
        image: composer
        volumes:
            - ./app:/app
        command: install

# APP DIR -> /app 
